### ISSUE TITLE
Where is the ES6/ES2015 Version of this sdk?

### ISSUE THREAD

**Issue by ryanemax** [dreamfactorysoftware/angular2-sdk#4]
Where is the ES6/ES2015 Version of this sdk?

**Comment by drewpearce** [comment]
The sample app should work with ES5 or ES6 with no modifications. If you encounter any specific bugs related to ES6, please feel free to file an issue here on github.

https://github.com/dreamfactorysoftware/javascript-sdk is the straightforward js/jquery version.
